services:
  db:
      image: 'postgres:latest'
      environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: ecommerce
      volumes:
        - ./pgdata:/var/lib/postgresql/data
      ports:
        - "5432:5432"
        
  rabitmq:
      image: rabbitmq:3-management-alpine
      container_name: 'rabbitmqPedidos'
      environment:
        - RABBITMQ_DEFAULT_USER=dev
        - RABBITMQ_DEFAULT_PASS=senhadev
      ports:
        - 5672:5672
        - 15672:15672
      volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq/
      networks:
        - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge