services:
  db:
      image: 'postgres:latest'
      environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: ecommerce
      volumes:
        - ./pgdata:/var/lib/postgresql/data
      ports:
        - "5432:5432"